import { createClient } from '@supabase/supabase-js'

export const supabase = createClient('https://myulsofprjotlyergysn.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15dWxzb2ZwcmpvdGx5ZXJneXNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTA4NzgsImV4cCI6MjA2MDgyNjg3OH0.Fo63RGGTcR6d9BCgd8VGzerFOFcBW2s064uym85i5KU')